Update messages.json
ysard/cookie-quick-manager pull request #36
Opened 2018-08-16 14:50 UTC by cyanotyp

added missing german translations

2018-08-19 19:48 UTC, ysard requested changes
Hi, thank you very much for these translations!
I made 2 request changes, and after that i will merge this PR ;)
PS: If you want to view entries that are in English version of messages.json and that are not in the German one, on Linux:
diff src/_locales/de/messages.json src/_locales/en/messages.json | grep ": {"

2018-08-19 19:48 UTC, ysard commented on src/_locales/de/messages.json
> +    "message": "Private browsing",
If this is justified in the German version of Firefox, could you translate these 3 sections please? 
(container_all, container_default, container_private)

2018-08-19 19:48 UTC, ysard commented on src/_locales/de/messages.json
> -    "message": "First-Party Isolation verhindert, dass Drittanbieter Cookies verwenden, um den Benutzer auf verschiedenen Websites zu identifizieren (siehe Optionen).",
Could you review the German version of this translation which has been deleted please?

2018-08-20 08:04 UTC, cyanotyp commented on src/_locales/de/messages.json
> -    "message": "First-Party Isolation verhindert, dass Drittanbieter Cookies verwenden, um den Benutzer auf verschiedenen Websites zu identifizieren (siehe Optionen).",
reverted the accidently deleted text

2018-08-20 08:05 UTC, cyanotyp commented
added the missing translations, for "Private Browsing" there is no common german translation, a word-wise translation does not make sense in german :)

2018-08-26 14:32 UTC, merged

2018-08-26 14:33 UTC, ysard commented
Thank you very very much, I'm back and I integrate all this in the next version :)